name: fortheforgotten
favicon: null
layout_spectrum: 0.010464134626090527
typography_spectrum: 0.5613667138386518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.24417559360153973
  lightness: 0.5601402656175196
  saturation: 0.29920649016276
  rhythmicContrast: 0.6279824895318598
purpose: []
